//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MFCFinalProjectRestUpdate.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MFC_FINAL_PROJECT_REST_UPDATE_DIALOG 102
#define IDR_MAINFRAME                   128
#define Manager_Dialog                  132
#define IDB_Success                     134
#define IDB_Error                       135
#define Main_Menu_Application           136
#define NewOrder                        138
#define NewOrderB                       140
#define ManagerDialog                   142
#define IDB_BITMAP1                     147
#define IDB_Logo                        147
#define IDC_EDIT_B_Name                 1000
#define IDC_Save_B_Settings             1001
#define IDC_EDIT_B_Telephone            1002
#define IDC_EDIT_B_Address              1003
#define IDC_EDIT_OpenHours              1004
#define curr_date                       1006
#define n_test                          1007
#define Market_DLG                      1007
#define Tel_test                        1008
#define validate_s1                     1016
#define validate_s2                     1017
#define validate_s3                     1018
#define validate_s4                     1019
#define validate_s5                     1020
#define validate_e1                     1021
#define validate_e2                     1022
#define validate_e3                     1023
#define validate_e4                     1024
#define validate_e5                     1025
#define IDC_EDIT_CloseHours             1027
#define IDC_BUTTON1                     1029
#define ActiveCustomerss                1039
#define CustomersList                   1044
#define NewRestOrder                    1045
#define IDC_EDIT23                      1091
#define NewOrderClick                   1124
#define OrderButcherRadio               1125
#define CFirsrN_V1                      1126
#define CFirsrN_V2                      1127
#define CFirsrN_V3                      1128
#define CFirsrN_V4                      1129
#define CFirsrN_X1                      1130
#define CFirsrN_X2                      1131
#define CFirsrN_X3                      1132
#define CFirsrN_X4                      1133
#define InputCustFname                  1134
#define InputCustLname                  1135
#define InputCustPNum                   1136
#define InputCustAddress                1137
#define AddCustomerClick                1138
#define Err_PhoneNum                    1139
#define EditCus                         1140
#define DeleteCus                       1141
#define SearchBTN                       1142
#define SearchField                     1143
#define Cola_sup                        1144
#define Soda_sup                        1145
#define Lemonade_sup                    1146
#define PinkLemonade_sup                1147
#define PrintTest                       1148
#define BalanceMarket                   1149
#define Err_order                       1149
#define Total_strMarket                 1150
#define Total_str                       1150
#define OpenMarket                      1152
#define BalanceText                     1153
#define ColaQty                         1154
#define SodaQty                         1155
#define LemonadeQty                     1156
#define PinkLemonadeQty                 1157
#define OrderList                       1159
#define OrdersTab                       1160
#define OrderListButcher                1161
#define TomatoQty                       1162
#define PickleQty                       1163
#define OnionQty                        1164
#define LettuceQty                      1165
#define PotatoQty                       1166
#define BurgerKg                        1167
#define WagyuKg                         1168
#define AngusKg                         1169
#define RibsKg                          1170
#define WhiteQty                        1171
#define WholeWheatQty                   1172
#define Tomato_sup                      1173
#define Pickle_sup                      1174
#define Onion_sup                       1175
#define Lettuce_sup                     1176
#define Potato_sup                      1177
#define Burger_sup                      1178
#define Wagyu_sup                       1179
#define Angus_sup                       1180
#define Ribs_sup                        1181
#define White_sup                       1182
#define WholeWheat_sup                  1183
#define FrenchFries_sup                 1184
#define OnionRings_Sup                  1185
#define Cb_Burger                       1186
#define RangeBurger                     1187
#define BurgerKgText                    1188
#define Cb_Wagyu                        1189
#define WagyuKgText                     1190
#define RangeWagyu                      1191
#define Cb_Angus                        1192
#define Cb_Ribs                         1193
#define RibsKgText                      1194
#define AngusKgText                     1195
#define RangeAngus                      1196
#define RangeRibs                       1197
#define IDTotal                         1198
#define IDC_errorIMG                    1199
#define IDC_errorTXT                    1200
#define DateID                          1201
#define B_nameID                        1202
#define B_AddID                         1203
#define B_TelID                         1204
#define IDC_CUSTOM1                     1205
#define Cb_Tomato_Salad                 1206
#define Cb_Pickle_Salad                 1207
#define Cb_Onion_Salad                  1208
#define Cb_Lettuce_Salad                1209
#define AddSalad_ID                     1210
#define Id_100g                         1211
#define Id_220g                         1212
#define Id_350g                         1213
#define ID_DoubleBurger                 1214
#define M_ID                            1216
#define MW_ID                           1217
#define WD_ID                           1218
#define id_NoTomato                     1219
#define id_NoPickle                     1220
#define id_NoOnion                      1221
#define id_NoLettuce                    1222
#define id_WithoutAll_Btn               1223
#define ID_b_w                          1224
#define ID_b_whole                      1225
#define id_fries                        1226
#define id_OnionRings                   1227
#define id_PLemonade                    1228
#define id_Lemonade                     1229
#define id_Soda                         1230
#define id_Cola                         1231
#define btnOrderComplete                1232
#define error_txt                       1233
#define error_img                       1234
#define error_msg                       1235
#define TotalProfit                     1236
#define TotalProfitFinance              1237
#define TotalProfitB                    1238
#define TotalProfitRe                   1239
#define TotalProfitRest                 1240
#define TotalOrdersID                   1241
#define RestPrecent                     1242
#define ButcherPercent                  1243
#define ButcherPrecent                  1243
#define rpre                            1245
#define bpre                            1246
#define errorOrders                     1247
#define ID_FILE_OPEN32771               32771
#define ID_FILE_SAVE32772               32772
#define ID_FILE_SAVEAS                  32773
#define ID_FILE_EXIT                    32774
#define ID_HELP_ABOUT                   32775
#define aboutdlg                        32776
#define saveSerialize                   32777
#define OpenSerialize                   32778

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1248
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
